### ISSUE TITLE
question: why use GenericTag as opposed to Context.Tag

### ISSUE THREAD

**Issue by adrian-gierakowski** [tim-smart/dfx#3]
hi, just a quick question: why, after recent upgrade of effect, have you opted for using `GenericTag` instead of the class based pattern advertised on effect website (`class MyService extends Context.Tag("MyService")<...>`)

was it just the fastest path to adapt to the new api or was there any other factor? 

Thanks!

**Comment by tim-smart** [comment]
There wasn't really a need to switch, as unique identifiers are already made for all of the services.

**Comment by adrian-gierakowski** [comment]
Thanks. Just asking as I was using this project previously as the reference for my explorations.  Would you say then that in a new project one should use the class approach? Is there any practical difference between the two? Thanks again!

**Comment by tim-smart** [comment]
The discord-bot project that uses this library is more application level code. I used Context.Tag there.
