### ISSUE TITLE
Type inference error

### ISSUE THREAD

**Issue by ethanniser** [tim-smart/dfx#4]
starting from this line: https://github.com/tim-smart/dfx/blob/main/src/gateway.ts#L27

```
The inferred type of 'DiscordLive' cannot be named without a reference to 
'.pnpm/dfx@0.101.1_@effect+platform@0.65.1_@effect+schema@0.72.3_effect@3.9.0__effect@3.9.0__effect@3.9.0/node_modules/@effect/platform/HttpClient'. 
This is likely not portable. A type annotation is necessary.
```

<img width="769" alt="image" src="https://github.com/user-attachments/assets/0fd93036-c92b-454c-883c-e47ac92b3ee1">

leads to `any` in requirements when importing

**Comment by tim-smart** [comment]
Try the latest release
